language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.8
install:
  - pip install coveralls
script:
  - coverage run --source=maintenance_mode manage.py test
after_success:
  - coveralls
