language: python
python: 3.5
env:
  - TOX_ENV=py27-17
  - TOX_ENV=py27-18
  - TOX_ENV=py27-19
  - TOX_ENV=py27-110
  - TOX_ENV=py34-17
  - TOX_ENV=py34-18
  - TOX_ENV=py34-19
  - TOX_ENV=py34-110
  - TOX_ENV=py35-18
  - TOX_ENV=py35-19
  - TOX_ENV=py35-110
  #- TOX_ENV=py36-18
  #- TOX_ENV=py36-19
  #- TOX_ENV=py36-110
install:
  - pip install flake8
  - pip install tox
before_script:
  - flake8 .
script:
  - tox -e $TOX_ENV
sudo: false
